version: "3.5"

services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=exercism
    volumes:
      - .:/var/www/exercism
    networks:
      - exercism

networks:
  exercism:
